# Stolen from http://conda.pydata.org/docs/travis.html
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
install:
  - python setup.py install

script: python -c 'import pyrle; print(pyrle.__version__)'
# functionality is tested in the pyranges package
