language: python
python:
  - "3.6"
install:
  - pip install cython pytest hypothesis
  - pip install sorted_nearest ncls
  - sudo apt-get install -y r-base
  - echo 'source("http://bioconductor.org/biocLite.R"); biocLite("S4Vectors"); biocLite("GenomicRanges")' > install.R
  - cat install.R
  - sudo Rscript --vanilla install.R
  - python setup.py install
  - python setup.py build_ext --inplace
  - ls tests

script:
  - python -c "import pyrle; print(pyrle.__version__)"
  - py.test -v
